//  GeneratedSubmissions.swift
//  ReactivChallengeKit
//
//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved.
//

/// Auto-generated by scripts/generate-registry.sh — do not edit manually.

// MARK: - From Submissions/mithun/Components/CityLeaderboard.swift

import SwiftUI

struct CityLeaderboard: View {
    let currentCauseId: String

    @State private var isExpanded = false

    var body: some View {
        DisclosureGroup(isExpanded: $isExpanded) {
            VStack(spacing: 0) {
                ForEach(CauseData.allCauses) { cause in
                    HStack(spacing: 10) {
                        Image(systemName: "leaf.fill")
                            .font(.system(size: 13))
                            .foregroundStyle(.green)

                        Text(cause.city)
                            .font(.system(size: 14, weight: cause.id == currentCauseId ? .bold : .medium))

                        Spacer()

                        Text("\(cause.mealsToday) meals")
                            .font(.system(size: 14, weight: .semibold))
                            .foregroundStyle(.green)
                    }
                    .padding(.vertical, 10)
                    .padding(.horizontal, 4)

                    if cause.id != CauseData.allCauses.last?.id {
                        Divider()
                    }
                }
            }
            .padding(.top, 8)
        } label: {
            HStack(spacing: 6) {
                Image(systemName: "chart.bar.fill")
                    .foregroundStyle(.green)
                    .font(.system(size: 14))
                Text("City Leaderboard")
                    .font(.system(size: 15, weight: .semibold))
            }
        }
        .tint(.green)
    }
}

// MARK: - From Submissions/mithun/Components/GoalProgressBar.swift

import SwiftUI

struct GoalProgressBar: View {
    let current: Int
    let goal: Int

    @State private var animatedProgress: CGFloat = 0

    private var targetProgress: CGFloat {
        guard goal > 0 else { return 0 }
        return min(CGFloat(current) / CGFloat(goal), 1.0)
    }

    var body: some View {
        VStack(spacing: 8) {
            HStack {
                Text("\(current) / \(goal) meals today")
                    .font(.system(size: 14, weight: .bold))
                Spacer()
                Text("\(Int(targetProgress * 100))%")
                    .font(.system(size: 14, weight: .semibold))
                    .foregroundStyle(.green)
            }

            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    RoundedRectangle(cornerRadius: 6)
                        .fill(Color(.systemGray5))
                        .frame(height: 12)

                    RoundedRectangle(cornerRadius: 6)
                        .fill(.green)
                        .frame(width: geo.size.width * animatedProgress, height: 12)
                }
            }
            .frame(height: 12)
        }
        .onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                withAnimation(.easeOut(duration: 1.0)) {
                    animatedProgress = targetProgress
                }
            }
        }
    }
}

// MARK: - From Submissions/mithun/GiveClipExperience.swift

import SwiftUI

struct GiveClipExperience: ClipExperience {
    static let urlPattern = "givekit.ca/cause/:causeId"
    static let clipName = "GiveClip"
    static let clipDescription = "Tap a food bank donation bin. Give in 20 seconds. Watch the counter move."
    static let teamName = "Mithun"
    static let touchpoint: JourneyTouchpoint = .onSite
    static let invocationSource: InvocationSource = .nfcTag

    let context: ClipContext
    @StateObject private var donationState: DonationState

    init(context: ClipContext) {
        self.context = context
        let causeId = context.pathParameters["causeId"] ?? "hamilton-food-share"
        _donationState = StateObject(wrappedValue: DonationState(causeId: causeId))
    }

    private var cause: CauseData {
        donationState.cause
    }

    var body: some View {
        ZStack {
            ClipBackground()

            Group {
                switch donationState.currentScreen {
                case .landing:
                    CauseLandingView(cause: cause)
                case .amount:
                    amountPlaceholder
                case .payment:
                    paymentPlaceholder
                case .confirmation:
                    confirmationPlaceholder
                }
            }
            .animation(.spring(duration: 0.35), value: donationState.currentScreen)
        }
        .environmentObject(donationState)
    }

    // MARK: - Placeholder screens (replaced in Phases 2–4)

    private var amountPlaceholder: some View {
        ScrollView {
            VStack(spacing: 20) {
                ClipHeader(
                    title: "How much would you like to give?",
                    subtitle: "Every dollar feeds a neighbour",
                    systemImage: "dollarsign.circle"
                )
                .padding(.top, 16)

                Text("$\(donationState.selectedAmount)")
                    .font(.system(size: 48, weight: .bold))
                    .foregroundStyle(.green)

                ClipActionButton(title: "Continue to Give", icon: "arrow.right.circle.fill") {
                    withAnimation { donationState.currentScreen = .payment }
                }
            }
            .padding(.bottom, 16)
        }
        .scrollIndicators(.hidden)
    }

    private var paymentPlaceholder: some View {
        ScrollView {
            VStack(spacing: 20) {
                ClipHeader(
                    title: "Confirm Your Gift",
                    subtitle: "$\(donationState.selectedAmount) to \(cause.name)",
                    systemImage: "creditcard"
                )
                .padding(.top, 16)

                ClipActionButton(title: "Give with Apple Pay", icon: "apple.logo") {
                    withAnimation { donationState.currentScreen = .confirmation }
                }
            }
            .padding(.bottom, 16)
        }
        .scrollIndicators(.hidden)
    }

    private var confirmationPlaceholder: some View {
        VStack(spacing: 16) {
            Spacer()
            ClipSuccessOverlay(
                message: "You just fed a family in \(cause.city) today."
            )
            Spacer()
        }
    }
}

// MARK: - From Submissions/mithun/Models/CauseData.swift

import Foundation

struct CauseData: Identifiable {
    let id: String
    let name: String
    let city: String
    let foundedYear: Int
    let mealsToday: Int
    let dailyGoal: Int
    let donorsThisWeek: Int
    let scenario: String
    let causeOptions: [String]

    var progress: Double {
        guard dailyGoal > 0 else { return 0 }
        return Double(mealsToday) / Double(dailyGoal)
    }

    static let allCauses: [CauseData] = [
        CauseData(
            id: "hamilton-food-share",
            name: "Hamilton Food Share",
            city: "Hamilton, ON",
            foundedYear: 1984,
            mealsToday: 848,
            dailyGoal: 1000,
            donorsThisWeek: 94,
            scenario: "A single mom skipped lunch so her kids could eat. Your gift means she doesn't have to choose.",
            causeOptions: ["Emergency food hampers", "Children's breakfast"]
        ),
        CauseData(
            id: "toronto-daily-bread",
            name: "Daily Bread Food Bank",
            city: "Toronto, ON",
            foundedYear: 1983,
            mealsToday: 1204,
            dailyGoal: 1500,
            donorsThisWeek: 217,
            scenario: "A retired teacher lines up before dawn. Your gift keeps the shelves stocked when she arrives.",
            causeOptions: ["Hot meal programs", "Grocery essentials"]
        ),
        CauseData(
            id: "vancouver-food-bank",
            name: "Greater Vancouver Food Bank",
            city: "Vancouver, BC",
            foundedYear: 1982,
            mealsToday: 673,
            dailyGoal: 900,
            donorsThisWeek: 156,
            scenario: "A student chose rent over food this month. Your gift makes sure no one goes hungry tonight.",
            causeOptions: ["Community kitchen", "Student meal packs"]
        ),
    ]

    static func cause(for id: String) -> CauseData {
        allCauses.first { $0.id == id } ?? allCauses[0]
    }
}

// MARK: - From Submissions/mithun/Models/DonationState.swift

import SwiftUI
internal import Combine

enum DonationScreen: Equatable {
    case landing
    case amount
    case payment
    case confirmation
}

final class DonationState: ObservableObject {
    @Published var currentScreen: DonationScreen = .landing
    @Published var selectedAmount: Int = 10
    @Published var selectedCause: String
    @Published var roundUpSelected: Bool = false
    @Published var causeDirection: String = ""
    @Published var isProcessingPayment: Bool = false

    init(causeId: String = "hamilton-food-share") {
        self.selectedCause = causeId
        let cause = CauseData.cause(for: causeId)
        if let first = cause.causeOptions.first {
            self.causeDirection = first
        }
    }

    var cause: CauseData {
        CauseData.cause(for: selectedCause)
    }

    var finalAmount: Int {
        roundUpSelected && selectedAmount == 10 ? 12 : selectedAmount
    }

    var impactLabel: String {
        switch selectedAmount {
        case 5: return "Feed 1 child today"
        case 10: return "Feed a family for a day"
        case 25: return "Stock a shelf for a week"
        default: return "Make a difference today"
        }
    }
}

// MARK: - From Submissions/mithun/Views/CauseLandingView.swift

import SwiftUI

struct CauseLandingView: View {
    let cause: CauseData
    @EnvironmentObject var donationState: DonationState

    var body: some View {
        ScrollView {
            VStack(spacing: 24) {
                Image(systemName: "fork.knife")
                    .font(.system(size: 40, weight: .medium))
                    .foregroundStyle(.white)
                    .frame(width: 80, height: 80)
                    .background(.green, in: Circle())
                    .padding(.top, 24)

                VStack(spacing: 4) {
                    Text(cause.name)
                        .font(.system(size: 28, weight: .bold))
                        .multilineTextAlignment(.center)
                    Text(cause.city)
                        .font(.system(size: 16))
                        .foregroundStyle(.secondary)
                }

                Text("Neighbours helping neighbours in \(cause.city)")
                    .font(.system(size: 16).italic())
                    .foregroundStyle(.green)

                Text(cause.scenario)
                    .font(.system(size: 14))
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
                    .lineLimit(2)
                    .padding(.horizontal, 32)

                GoalProgressBar(current: cause.mealsToday, goal: cause.dailyGoal)
                    .padding(.horizontal, 16)

                HStack(spacing: 4) {
                    Image(systemName: "person.2.fill")
                        .font(.system(size: 12))
                        .foregroundStyle(.secondary)
                    Text("\(cause.donorsThisWeek) people gave in \(cause.city) this week")
                        .font(.system(size: 13))
                        .foregroundStyle(.secondary)
                }

                CityLeaderboard(currentCauseId: cause.id)
                    .padding(.horizontal, 16)

                Button {
                    withAnimation(.spring(duration: 0.35)) {
                        donationState.currentScreen = .amount
                    }
                } label: {
                    Text("Feed Someone Today")
                        .font(.system(size: 18, weight: .bold))
                        .foregroundStyle(.white)
                        .frame(maxWidth: .infinity)
                        .frame(height: 56)
                        .background(.green, in: RoundedRectangle(cornerRadius: 16))
                }
                .padding(.horizontal, 16)
            }
            .padding(.bottom, 16)
        }
        .scrollIndicators(.hidden)
    }
}

