//  GeneratedSubmissions.swift
//  ReactivChallengeKit
//
//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved.
//

/// Auto-generated by scripts/generate-registry.sh — do not edit manually.

// MARK: - From Submissions/clipbet/ClipBetComponents.swift

//  ClipBetComponents.swift
//  ClipBet
//
//  Reusable UI components following the editorial-minimal design system.
//  Cormorant Garamond for emotional/structural content.
//  DM Mono for functional UI.
//

import SwiftUI

// MARK: - Status Indicator

struct StatusIndicator: View {
    let status: EventStatus
    @State private var pulsing = false

    var body: some View {
        HStack(spacing: 8) {
            Circle()
                .fill(status.dotColor)
                .frame(width: 6, height: 6)
                .opacity(pulsing ? 0.4 : 1.0)

            Text(status.rawValue)
                .font(.custom("DM Mono", size: 11))
                .kerning(2)
                .foregroundColor(ClipBetColors.textSecondary)
                .textCase(.uppercase)
        }
        .onAppear {
            if status.isPulsing {
                withAnimation(.easeInOut(duration: 1.2).repeatForever(autoreverses: true)) {
                    pulsing = true
                }
            }
        }
    }
}

// MARK: - Outcome Row

struct OutcomeRow: View {
    let outcome: BetOutcome
    let percentage: Double
    let isFirst: Bool

    private var color: Color {
        isFirst ? ClipBetColors.yes : ClipBetColors.no
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text(outcome.name)
                    .font(.custom("DM Mono", size: 14))
                    .foregroundColor(ClipBetColors.textPrimary)

                Spacer()

                Text(String(format: "%.0f%%", percentage))
                    .font(.custom("Cormorant Garamond", size: 28))
                    .fontWeight(.light)
                    .foregroundColor(color)
            }

            // 3px progress bar
            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    Rectangle()
                        .fill(ClipBetColors.divider)
                        .frame(height: 3)

                    Rectangle()
                        .fill(color)
                        .frame(width: geo.size.width * (percentage / 100), height: 3)
                }
            }
            .frame(height: 3)

            HStack {
                Text(outcome.formattedAmount)
                    .font(.custom("DM Mono", size: 11))
                    .foregroundColor(ClipBetColors.textSecondary)

                Spacer()

                Text("\(outcome.betCount) bets")
                    .font(.custom("DM Mono", size: 11))
                    .foregroundColor(ClipBetColors.textFaint)
            }
        }
        .padding(.vertical, 16)
    }
}

// MARK: - Hairline Divider

struct ClipBetDivider: View {
    var body: some View {
        Rectangle()
            .fill(ClipBetColors.divider)
            .frame(height: 1)
    }
}

// MARK: - Vertical Divider

struct ClipBetVerticalDivider: View {
    var height: CGFloat = 40

    var body: some View {
        Rectangle()
            .fill(ClipBetColors.divider)
            .frame(width: 1, height: height)
    }
}

// MARK: - Dark Confirm Divider

struct ClipBetDarkDivider: View {
    var body: some View {
        Rectangle()
            .fill(Color.white.opacity(0.08))
            .frame(height: 1)
    }
}

// MARK: - Mono Label (Centered)

struct MonoLabel: View {
    let text: String

    var body: some View {
        Text(text)
            .font(.custom("DM Mono", size: 11))
            .kerning(1.8)
            .foregroundColor(ClipBetColors.textSecondary)
            .textCase(.uppercase)
            .multilineTextAlignment(.center)
    }
}

// MARK: - Mono Label (Left Aligned)

struct MonoLabelLeft: View {
    let text: String

    var body: some View {
        Text(text)
            .font(.custom("DM Mono", size: 10))
            .kerning(2)
            .foregroundColor(ClipBetColors.textSecondary)
            .textCase(.uppercase)
    }
}

// MARK: - Stat Column (Newspaper Style)

struct StatColumn: View {
    let value: String
    let label: String

    var body: some View {
        VStack(spacing: 4) {
            Text(value)
                .font(.custom("Cormorant Garamond", size: 26))
                .fontWeight(.light)
                .foregroundColor(ClipBetColors.textPrimary)

            Text(label)
                .font(.custom("DM Mono", size: 9))
                .kerning(1.6)
                .foregroundColor(ClipBetColors.textSecondary)
                .textCase(.uppercase)
        }
        .frame(maxWidth: .infinity)
    }
}

// MARK: - Primary CTA Button

struct ClipBetPrimaryButton: View {
    let title: String
    var icon: String? = nil
    var isEnabled: Bool = true
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            HStack(spacing: 8) {
                if let icon {
                    Image(systemName: icon)
                        .font(.system(size: 14))
                }
                Text(title)
                    .font(.custom("DM Mono", size: 13))
                    .kerning(2.4)
            }
            .foregroundColor(ClipBetColors.bg)
            .frame(maxWidth: .infinity)
            .padding(.vertical, 16)
            .background(isEnabled ? ClipBetColors.dark : ClipBetColors.textFaint)
            .clipShape(RoundedRectangle(cornerRadius: 2))
        }
        .disabled(!isEnabled)
    }
}

// MARK: - Secondary Button

struct ClipBetSecondaryButton: View {
    let title: String
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text(title)
                .font(.custom("DM Mono", size: 11))
                .kerning(1.4)
                .foregroundColor(ClipBetColors.textSecondary)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .overlay(
                    RoundedRectangle(cornerRadius: 2)
                        .stroke(ClipBetColors.divider, lineWidth: 1)
                )
        }
    }
}

// MARK: - Amount Selector Button

struct AmountButton: View {
    let amount: Double
    let isSelected: Bool
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text("$\(Int(amount))")
                .font(.custom("DM Mono", size: 14))
                .foregroundColor(isSelected ? ClipBetColors.bg : ClipBetColors.textPrimary)
                .padding(.horizontal, 16)
                .padding(.vertical, 12)
                .background(isSelected ? ClipBetColors.dark : Color.clear)
                .overlay(
                    RoundedRectangle(cornerRadius: 2)
                        .stroke(isSelected ? Color.clear : ClipBetColors.divider, lineWidth: 1)
                )
                .clipShape(RoundedRectangle(cornerRadius: 2))
        }
    }
}

// MARK: - Back Button

struct ClipBetBackButton: View {
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            HStack(spacing: 4) {
                Image(systemName: "arrow.left")
                    .font(.system(size: 12))
                Text("BACK")
                    .font(.custom("DM Mono", size: 11))
                    .kerning(1.6)
            }
            .foregroundColor(ClipBetColors.textSecondary)
        }
    }
}

// MARK: - Confirm Row (Dark Background)

struct ConfirmRow: View {
    let label: String
    let value: String
    var isMultiline: Bool = false
    var valueColor: Color = .white

    var body: some View {
        HStack(alignment: isMultiline ? .top : .center) {
            Text(label)
                .font(.custom("DM Mono", size: 10))
                .kerning(1.6)
                .foregroundColor(ClipBetColors.textFaint)
                .frame(width: 90, alignment: .leading)

            Text(value)
                .font(.custom("DM Mono", size: 13))
                .foregroundColor(valueColor)
                .lineLimit(isMultiline ? 3 : 1)

            Spacer()
        }
        .padding(.vertical, 10)
    }
}

// MARK: - Receipt Row (Light Background)

struct ReceiptRow: View {
    let label: String
    let value: String

    var body: some View {
        HStack {
            Text(label)
                .font(.custom("DM Mono", size: 10))
                .kerning(1.6)
                .foregroundColor(ClipBetColors.textSecondary)
                .frame(width: 90, alignment: .leading)

            Text(value)
                .font(.custom("DM Mono", size: 13))
                .foregroundColor(ClipBetColors.textPrimary)
                .lineLimit(2)

            Spacer()
        }
        .padding(.vertical, 8)
    }
}

// MARK: - Text Field (Editorial Style)

struct ClipBetTextField: View {
    let placeholder: String
    @Binding var text: String
    var keyboardType: UIKeyboardType = .default
    var autocapitalization: TextInputAutocapitalization = .never

    var body: some View {
        TextField(placeholder, text: $text)
            .font(.custom("DM Mono", size: 14))
            .foregroundColor(ClipBetColors.textPrimary)
            .padding(.horizontal, 16)
            .padding(.vertical, 14)
            .background(ClipBetColors.surface)
            .clipShape(RoundedRectangle(cornerRadius: 2))
            .textInputAutocapitalization(autocapitalization)
            .keyboardType(keyboardType)
    }
}

// MARK: - Tag Badge

struct ClipBetTag: View {
    let text: String
    var color: Color = ClipBetColors.accent

    var body: some View {
        Text(text)
            .font(.custom("DM Mono", size: 9))
            .kerning(1.2)
            .foregroundColor(color)
            .padding(.horizontal, 6)
            .padding(.vertical, 2)
            .overlay(
                RoundedRectangle(cornerRadius: 2)
                    .stroke(color, lineWidth: 1)
            )
    }
}

// MARK: - From Submissions/clipbet/ClipBetExperience.swift

//  ClipBetExperience.swift
//  ClipBet
//
//  Main App Clip experience. Entry point for the ClipBet prediction market.
//  Flow: Landing -> Place Bet -> Confirm (Apple Pay) -> Success
//
//  Scan QR at a venue. See the event. Place your bet. Done.
//

import SwiftUI

struct ClipBetExperience: ClipExperience {
    static let urlPattern = "clipbet.io/event/:eventId"
    static let clipName = "ClipBet"
    static let clipDescription = "Scan. Predict. Win. Hyperlocal prediction markets, no app, no account."
    static let teamName = "ClipBet"

    static let touchpoint: JourneyTouchpoint = .onSite
    static let invocationSource: InvocationSource = .qrCode

    let context: ClipContext

    // MARK: - Screen Flow

    enum Screen {
        case landing
        case placeBet
        case confirm
        case success
    }

    @State private var currentScreen: Screen = .landing
    @State private var event: PredictionEvent = ClipBetMockData.primaryEvent
    @State private var selectedOutcome: BetOutcome?
    @State private var betAmount: Double = 10
    @State private var nickname: String = ""
    @State private var email: String = ""
    @State private var customAmount: String = ""
    @State private var showCustomAmount = false
    @State private var appeared = false
    @State private var paymentManager = ClipBetPaymentManager()

    var body: some View {
        ZStack {
            ClipBetColors.bg.ignoresSafeArea()

            switch currentScreen {
            case .landing:
                landingView
                    .transition(.opacity)
            case .placeBet:
                placeBetView
                    .transition(.move(edge: .trailing).combined(with: .opacity))
            case .confirm:
                confirmView
                    .transition(.move(edge: .trailing).combined(with: .opacity))
            case .success:
                successView
                    .transition(.scale(scale: 0.95).combined(with: .opacity))
            }
        }
        .animation(.easeInOut(duration: 0.3), value: currentScreen)
        .onAppear {
            withAnimation(.easeOut(duration: 0.6).delay(0.1)) {
                appeared = true
            }
        }
    }

    // MARK: - Landing View

    private var landingView: some View {
        ScrollView {
            VStack(spacing: 0) {

                // Brand + Status
                VStack(spacing: 16) {
                    Text("ClipBet")
                        .font(.custom("Cormorant Garamond", size: 32))
                        .fontWeight(.light)
                        .foregroundColor(ClipBetColors.textPrimary)
                        .opacity(appeared ? 1 : 0)
                        .offset(y: appeared ? 0 : 8)

                    StatusIndicator(status: event.status)
                }
                .padding(.top, 24)
                .padding(.bottom, 20)

                ClipBetDivider()

                // Event question
                VStack(spacing: 12) {
                    Text(event.name)
                        .font(.custom("Cormorant Garamond", size: 28))
                        .fontWeight(.light)
                        .foregroundColor(ClipBetColors.textPrimary)
                        .multilineTextAlignment(.center)
                        .lineSpacing(4)
                        .opacity(appeared ? 1 : 0)
                        .offset(y: appeared ? 0 : 12)

                    MonoLabel(text: event.location)
                }
                .padding(.horizontal, 32)
                .padding(.vertical, 28)

                ClipBetDivider()

                // Pool stats
                HStack(spacing: 0) {
                    StatColumn(value: event.formattedPool, label: "TOTAL POOL")
                    ClipBetVerticalDivider()
                    StatColumn(value: "\(event.totalBettors)", label: "BETTORS")
                    ClipBetVerticalDivider()
                    StatColumn(value: "5%", label: "PLATFORM FEE")
                }
                .padding(.vertical, 20)

                ClipBetDivider()

                // Outcomes
                VStack(spacing: 0) {
                    ForEach(Array(event.outcomes.enumerated()), id: \.element.id) { index, outcome in
                        OutcomeRow(
                            outcome: outcome,
                            percentage: event.percentage(for: outcome),
                            isFirst: index == 0
                        )
                        if index < event.outcomes.count - 1 {
                            ClipBetDivider()
                        }
                    }
                }
                .padding(.horizontal, 24)
                .padding(.vertical, 16)

                ClipBetDivider()

                // CTA
                VStack(spacing: 12) {
                    ClipBetPrimaryButton(title: "PLACE A BET") {
                        withAnimation { currentScreen = .placeBet }
                    }
                }
                .padding(.horizontal, 24)
                .padding(.vertical, 24)

                // Organizer
                MonoLabel(text: "organized by \(event.organizer)")
                    .padding(.bottom, 8)

                MonoLabel(text: event.timeSinceCreated + " ago")
                    .padding(.bottom, 24)
            }
        }
        .scrollIndicators(.hidden)
    }

    // MARK: - Place Bet View

    private var placeBetView: some View {
        ScrollView {
            VStack(spacing: 0) {

                // Header
                HStack {
                    ClipBetBackButton {
                        withAnimation { currentScreen = .landing }
                    }
                    Spacer()
                }
                .padding(.horizontal, 24)
                .padding(.top, 16)

                Text("Place Your Bet")
                    .font(.custom("Cormorant Garamond", size: 28))
                    .fontWeight(.light)
                    .foregroundColor(ClipBetColors.textPrimary)
                    .padding(.top, 20)
                    .padding(.bottom, 8)

                MonoLabel(text: event.name)
                    .padding(.horizontal, 32)
                    .padding(.bottom, 24)

                ClipBetDivider()

                // Email
                VStack(alignment: .leading, spacing: 8) {
                    MonoLabelLeft(text: "EMAIL")
                    ClipBetTextField(
                        placeholder: "your@email.com",
                        text: $email,
                        keyboardType: .emailAddress
                    )
                }
                .padding(.horizontal, 24)
                .padding(.vertical, 20)

                ClipBetDivider()

                // Nickname
                VStack(alignment: .leading, spacing: 8) {
                    HStack {
                        MonoLabelLeft(text: "NICKNAME")
                        Spacer()
                        Text("optional")
                            .font(.custom("DM Mono", size: 10))
                            .foregroundColor(ClipBetColors.textFaint)
                    }
                    ClipBetTextField(
                        placeholder: "Anonymous",
                        text: $nickname
                    )
                }
                .padding(.horizontal, 24)
                .padding(.vertical, 20)

                ClipBetDivider()

                // Outcome selection
                VStack(alignment: .leading, spacing: 12) {
                    MonoLabelLeft(text: "SELECT OUTCOME")
                        .padding(.horizontal, 24)

                    ForEach(event.outcomes) { outcome in
                        let isSelected = selectedOutcome?.id == outcome.id
                        let isYes = event.outcomes.first?.id == outcome.id

                        Button {
                            withAnimation(.easeOut(duration: 0.2)) {
                                selectedOutcome = outcome
                            }
                        } label: {
                            HStack {
                                Circle()
                                    .fill(isSelected
                                          ? (isYes ? ClipBetColors.yes : ClipBetColors.no)
                                          : ClipBetColors.divider)
                                    .frame(width: 8, height: 8)

                                Text(outcome.name)
                                    .font(.custom("DM Mono", size: 14))
                                    .foregroundColor(isSelected ? ClipBetColors.textPrimary : ClipBetColors.textSecondary)

                                Spacer()

                                Text(String(format: "%.0f%%", event.percentage(for: outcome)))
                                    .font(.custom("Cormorant Garamond", size: 22))
                                    .fontWeight(.light)
                                    .foregroundColor(isSelected
                                                     ? (isYes ? ClipBetColors.yes : ClipBetColors.no)
                                                     : ClipBetColors.textFaint)
                            }
                            .padding(.horizontal, 20)
                            .padding(.vertical, 16)
                            .background(isSelected
                                        ? (isYes ? ClipBetColors.yesFill : ClipBetColors.noFill)
                                        : Color.clear)
                            .clipShape(RoundedRectangle(cornerRadius: 2))
                        }
                        .padding(.horizontal, 16)
                    }
                }
                .padding(.vertical, 20)

                ClipBetDivider()

                // Bet amount
                VStack(alignment: .leading, spacing: 12) {
                    MonoLabelLeft(text: "BET AMOUNT")
                        .padding(.horizontal, 24)

                    HStack(spacing: 8) {
                        ForEach([5.0, 10.0, 25.0], id: \.self) { amount in
                            AmountButton(
                                amount: amount,
                                isSelected: !showCustomAmount && betAmount == amount
                            ) {
                                showCustomAmount = false
                                customAmount = ""
                                betAmount = amount
                            }
                        }

                        Button {
                            showCustomAmount = true
                            betAmount = 0
                        } label: {
                            Text("CUSTOM")
                                .font(.custom("DM Mono", size: 12))
                                .kerning(1)
                                .foregroundColor(showCustomAmount ? ClipBetColors.bg : ClipBetColors.textSecondary)
                                .padding(.horizontal, 16)
                                .padding(.vertical, 12)
                                .background(showCustomAmount ? ClipBetColors.dark : Color.clear)
                                .overlay(
                                    RoundedRectangle(cornerRadius: 2)
                                        .stroke(ClipBetColors.divider, lineWidth: 1)
                                )
                                .clipShape(RoundedRectangle(cornerRadius: 2))
                        }
                    }
                    .padding(.horizontal, 24)

                    if showCustomAmount {
                        HStack {
                            Text("$")
                                .font(.custom("Cormorant Garamond", size: 24))
                                .fontWeight(.light)
                                .foregroundColor(ClipBetColors.textPrimary)
                            TextField("0", text: $customAmount)
                                .font(.custom("Cormorant Garamond", size: 24))
                                .fontWeight(.light)
                                .foregroundColor(ClipBetColors.textPrimary)
                                .keyboardType(.numberPad)
                                .onChange(of: customAmount) { _, newValue in
                                    betAmount = Double(newValue) ?? 0
                                }
                        }
                        .padding(.horizontal, 16)
                        .padding(.vertical, 12)
                        .background(ClipBetColors.surface)
                        .clipShape(RoundedRectangle(cornerRadius: 2))
                        .padding(.horizontal, 24)
                    }
                }
                .padding(.vertical, 20)

                ClipBetDivider()

                // Estimated return
                if let outcome = selectedOutcome, betAmount > 0 {
                    let est = event.estimatedReturn(betAmount: betAmount, for: outcome)
                    VStack(spacing: 4) {
                        MonoLabel(text: "ESTIMATED RETURN")
                        Text(String(format: "$%.2f", est))
                            .font(.custom("Cormorant Garamond", size: 36))
                            .fontWeight(.light)
                            .foregroundColor(ClipBetColors.yes)
                    }
                    .padding(.vertical, 20)

                    ClipBetDivider()
                }

                // Review button
                let canProceed = selectedOutcome != nil && betAmount >= event.minimumBet && !email.isEmpty
                ClipBetPrimaryButton(
                    title: "REVIEW & PAY",
                    icon: "apple.logo",
                    isEnabled: canProceed
                ) {
                    withAnimation { currentScreen = .confirm }
                }
                .padding(.horizontal, 24)
                .padding(.vertical, 24)

                MonoLabel(text: "min bet: $\(Int(event.minimumBet))")
                    .padding(.bottom, 24)
            }
        }
        .scrollIndicators(.hidden)
    }

    // MARK: - Confirm View (Dark Modal)

    private var confirmView: some View {
        VStack(spacing: 0) {
            Spacer()

            VStack(spacing: 0) {
                // Header
                HStack {
                    Button {
                        withAnimation { currentScreen = .placeBet }
                    } label: {
                        HStack(spacing: 4) {
                            Image(systemName: "arrow.left")
                                .font(.system(size: 12))
                            Text("BACK")
                                .font(.custom("DM Mono", size: 11))
                                .kerning(1.6)
                        }
                        .foregroundColor(ClipBetColors.textFaint)
                    }
                    Spacer()
                }
                .padding(.horizontal, 24)
                .padding(.top, 24)

                Text("Confirm Bet")
                    .font(.custom("Cormorant Garamond", size: 28))
                    .fontWeight(.light)
                    .foregroundColor(ClipBetColors.bg)
                    .padding(.top, 16)
                    .padding(.bottom, 24)

                // Bet details
                VStack(spacing: 0) {
                    ConfirmRow(label: "EVENT", value: event.name, isMultiline: true)
                    ClipBetDarkDivider()
                    ConfirmRow(label: "PREDICTION", value: selectedOutcome?.name ?? "")
                    ClipBetDarkDivider()
                    ConfirmRow(label: "AMOUNT", value: String(format: "$%.0f", betAmount))
                    ClipBetDarkDivider()
                    if let outcome = selectedOutcome {
                        let est = event.estimatedReturn(betAmount: betAmount, for: outcome)
                        ConfirmRow(label: "EST. RETURN", value: String(format: "$%.2f", est), valueColor: ClipBetColors.yes)
                        ClipBetDarkDivider()
                    }
                    ConfirmRow(label: "AS", value: nickname.isEmpty ? "Anonymous" : nickname)
                    ClipBetDarkDivider()
                    ConfirmRow(label: "CONTACT", value: email)
                }
                .padding(.horizontal, 24)
                .padding(.vertical, 16)

                // Payment status
                ClipBetPaymentStatus(state: paymentManager.paymentState)
                    .padding(.horizontal, 24)

                Spacer()

                // Apple Pay button + card fallback
                ClipBetApplePayButton(
                    amount: betAmount,
                    isEnabled: paymentManager.paymentState != .processing,
                    isProcessing: paymentManager.paymentState == .processing,
                    onTap: { processApplePayment() },
                    onCardFallback: { processCardPayment() }
                )
                .padding(.horizontal, 24)
                .padding(.bottom, 32)
            }
            .background(ClipBetColors.dark)
            .clipShape(RoundedRectangle(cornerRadius: 2))
        }
        .ignoresSafeArea(edges: .bottom)
    }

    // MARK: - Success View

    private var successView: some View {
        ScrollView {
            VStack(spacing: 0) {
                VStack(spacing: 16) {
                    Image(systemName: "checkmark")
                        .font(.system(size: 32, weight: .light))
                        .foregroundColor(ClipBetColors.yes)
                        .padding(.top, 40)

                    Text("You're In")
                        .font(.custom("Cormorant Garamond", size: 36))
                        .fontWeight(.light)
                        .foregroundColor(ClipBetColors.textPrimary)

                    MonoLabel(text: "Bet placed successfully")
                }
                .padding(.bottom, 28)

                ClipBetDivider()

                // Receipt
                VStack(spacing: 0) {
                    ReceiptRow(label: "EVENT", value: event.name)
                    ReceiptRow(label: "YOUR PICK", value: selectedOutcome?.name ?? "")
                    ReceiptRow(label: "AMOUNT", value: String(format: "$%.0f", betAmount))
                    if let outcome = selectedOutcome {
                        let est = event.estimatedReturn(betAmount: betAmount, for: outcome)
                        ReceiptRow(label: "EST. RETURN", value: String(format: "$%.2f", est))
                    }
                    ReceiptRow(label: "NICKNAME", value: nickname.isEmpty ? "Anonymous" : nickname)
                    if case .success(let txId) = paymentManager.paymentState {
                        ReceiptRow(label: "TRANSACTION", value: txId)
                    }
                }
                .padding(.horizontal, 24)
                .padding(.vertical, 20)

                ClipBetDivider()

                // Pool standings
                VStack(spacing: 16) {
                    MonoLabel(text: "CURRENT STANDINGS")
                        .padding(.top, 20)

                    ForEach(event.outcomes) { outcome in
                        let pct = event.percentage(for: outcome)
                        let isYes = event.outcomes.first?.id == outcome.id
                        let isYours = outcome.id == selectedOutcome?.id

                        VStack(alignment: .leading, spacing: 6) {
                            HStack {
                                Text(outcome.name)
                                    .font(.custom("DM Mono", size: 13))
                                    .foregroundColor(ClipBetColors.textPrimary)

                                if isYours {
                                    ClipBetTag(text: "YOUR PICK")
                                }

                                Spacer()

                                Text(String(format: "%.0f%%", pct))
                                    .font(.custom("Cormorant Garamond", size: 24))
                                    .fontWeight(.light)
                                    .foregroundColor(isYes ? ClipBetColors.yes : ClipBetColors.no)
                            }

                            GeometryReader { geo in
                                ZStack(alignment: .leading) {
                                    Rectangle()
                                        .fill(ClipBetColors.divider)
                                        .frame(height: 3)
                                    Rectangle()
                                        .fill(isYes ? ClipBetColors.yes : ClipBetColors.no)
                                        .frame(width: geo.size.width * (pct / 100), height: 3)
                                }
                            }
                            .frame(height: 3)
                        }
                        .padding(.horizontal, 24)
                    }
                }
                .padding(.bottom, 24)

                ClipBetDivider()

                // Notification opt-in
                VStack(spacing: 12) {
                    MonoLabel(text: "GET NOTIFIED WHEN RESULTS ARE IN")

                    Button { } label: {
                        HStack(spacing: 8) {
                            Image(systemName: "bell")
                                .font(.system(size: 14))
                            Text("ENABLE NOTIFICATIONS")
                                .font(.custom("DM Mono", size: 12))
                                .kerning(1.6)
                        }
                        .foregroundColor(ClipBetColors.textPrimary)
                        .padding(.horizontal, 20)
                        .padding(.vertical, 14)
                        .overlay(
                            RoundedRectangle(cornerRadius: 2)
                                .stroke(ClipBetColors.divider, lineWidth: 1)
                        )
                    }
                }
                .padding(.vertical, 24)

                // Escrow info
                VStack(spacing: 4) {
                    MonoLabel(text: "FUNDS HELD IN ESCROW")
                    Text("Organizer has 24h to resolve. If unresolved, you get a full refund.")
                        .font(.custom("DM Mono", size: 10))
                        .foregroundColor(ClipBetColors.textFaint)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal, 32)
                }
                .padding(.bottom, 32)
            }
        }
        .scrollIndicators(.hidden)
    }

    // MARK: - Payment Actions

    private func processApplePayment() {
        paymentManager.selectedMethod = .applePay
        paymentManager.processBet(
            amount: betAmount,
            eventId: event.id,
            outcomeId: selectedOutcome?.id ?? UUID(),
            email: email,
            nickname: nickname.isEmpty ? "Anonymous" : nickname
        ) { success in
            if success {
                // Update pool with user bet
                if let idx = event.outcomes.firstIndex(where: { $0.id == selectedOutcome?.id }) {
                    event.outcomes[idx].totalAmount += betAmount
                    event.outcomes[idx].betCount += 1
                }
                withAnimation { currentScreen = .success }
            }
            // On failure, payment status view shows error, user can retry
        }
    }

    private func processCardPayment() {
        paymentManager.selectedMethod = .card
        paymentManager.processBet(
            amount: betAmount,
            eventId: event.id,
            outcomeId: selectedOutcome?.id ?? UUID(),
            email: email,
            nickname: nickname.isEmpty ? "Anonymous" : nickname
        ) { success in
            if success {
                if let idx = event.outcomes.firstIndex(where: { $0.id == selectedOutcome?.id }) {
                    event.outcomes[idx].totalAmount += betAmount
                    event.outcomes[idx].betCount += 1
                }
                withAnimation { currentScreen = .success }
            }
        }
    }
}

// MARK: - From Submissions/clipbet/ClipBetMockData.swift

//  ClipBetMockData.swift
//  ClipBet
//
//  Mock data for the hackathon demo.
//  In production this comes from the backend API.
//

import Foundation

enum ClipBetMockData {

    // MARK: - Organizers

    static let organizer1 = EventOrganizer(
        id: UUID(),
        appleUserId: "apple_001",
        stripeConnectId: "acct_mock_arena",
        tosAgreedAt: Calendar.current.date(byAdding: .day, value: -30, to: Date()),
        verifiedAt: Calendar.current.date(byAdding: .day, value: -30, to: Date()),
        eventsCreated: 12,
        disputesAgainst: 0,
        rating: 4.9
    )

    static let organizer2 = EventOrganizer(
        id: UUID(),
        appleUserId: "apple_002",
        stripeConnectId: "acct_mock_concert",
        tosAgreedAt: Calendar.current.date(byAdding: .day, value: -14, to: Date()),
        verifiedAt: Calendar.current.date(byAdding: .day, value: -14, to: Date()),
        eventsCreated: 5,
        disputesAgainst: 0,
        rating: 4.7
    )

    // MARK: - Outcomes

    static let outcomes1: [BetOutcome] = [
        BetOutcome(id: UUID(), name: "Raptors win", totalAmount: 1250, betCount: 23),
        BetOutcome(id: UUID(), name: "Celtics win", totalAmount: 890, betCount: 17),
    ]

    static let outcomes2: [BetOutcome] = [
        BetOutcome(id: UUID(), name: "Under 30 min", totalAmount: 340, betCount: 12),
        BetOutcome(id: UUID(), name: "30 to 60 min", totalAmount: 520, betCount: 18),
        BetOutcome(id: UUID(), name: "Over 60 min", totalAmount: 180, betCount: 7),
    ]

    static let outcomes3: [BetOutcome] = [
        BetOutcome(id: UUID(), name: "Yes, encore", totalAmount: 680, betCount: 31),
        BetOutcome(id: UUID(), name: "No encore", totalAmount: 220, betCount: 9),
    ]

    // MARK: - Events

    static let events: [PredictionEvent] = [
        PredictionEvent(
            id: UUID(),
            name: "Will the Raptors beat the Celtics tonight?",
            location: "Scotiabank Arena, Toronto",
            locationLat: 43.6435,
            locationLng: -79.3791,
            organizer: "ArenaHost",
            organizerId: organizer1.id,
            status: .live,
            outcomes: outcomes1,
            minimumBet: 5,
            bettingWindow: .stayOpen,
            createdAt: Calendar.current.date(byAdding: .minute, value: -47, to: Date()) ?? Date()
        ),
        PredictionEvent(
            id: UUID(),
            name: "How long will the opening act play?",
            location: "Rogers Centre, Toronto",
            locationLat: 43.6414,
            locationLng: -79.3894,
            organizer: "ConcertOps",
            organizerId: organizer2.id,
            status: .live,
            outcomes: outcomes2,
            minimumBet: 5,
            bettingWindow: .atStart,
            createdAt: Calendar.current.date(byAdding: .minute, value: -12, to: Date()) ?? Date()
        ),
        PredictionEvent(
            id: UUID(),
            name: "Will there be an encore?",
            location: "Massey Hall, Toronto",
            locationLat: 43.6543,
            locationLng: -79.3787,
            organizer: "LiveNation",
            organizerId: organizer1.id,
            status: .live,
            outcomes: outcomes3,
            minimumBet: 5,
            bettingWindow: .manual,
            createdAt: Calendar.current.date(byAdding: .hour, value: -1, to: Date()) ?? Date()
        ),
    ]

    static var primaryEvent: PredictionEvent { events[0] }

    // MARK: - Sample Bets

    static let sampleBets: [UserBet] = [
        UserBet(
            id: UUID(),
            eventId: events[0].id,
            outcomeId: outcomes1[0].id,
            amount: 25,
            nickname: "RaptorsFan99",
            email: "fan@example.com",
            status: .confirmed,
            payoutAmount: nil,
            payoutStatus: .none,
            createdAt: Calendar.current.date(byAdding: .minute, value: -30, to: Date()) ?? Date(),
            stripePaymentIntentId: "pi_mock_001"
        ),
        UserBet(
            id: UUID(),
            eventId: events[0].id,
            outcomeId: outcomes1[1].id,
            amount: 10,
            nickname: "Anonymous",
            email: "anon@example.com",
            status: .confirmed,
            payoutAmount: nil,
            payoutStatus: .none,
            createdAt: Calendar.current.date(byAdding: .minute, value: -22, to: Date()) ?? Date(),
            stripePaymentIntentId: "pi_mock_002"
        ),
    ]
}

// MARK: - From Submissions/clipbet/ClipBetModels.swift

//  ClipBetModels.swift
//  ClipBet
//
//  Data models for events, bets, organizers, and outcomes.
//  Based on the full backend schema (Part 8).
//

import Foundation
import SwiftUI

// MARK: - Design System Colors

enum ClipBetColors {
    static let bg           = Color(red: 250/255, green: 248/255, blue: 245/255) // FAF8F5
    static let surface      = Color(red: 240/255, green: 236/255, blue: 228/255) // F0ECE4
    static let divider      = Color(red: 226/255, green: 221/255, blue: 213/255) // E2DDD5
    static let textPrimary  = Color(red: 26/255,  green: 24/255,  blue: 20/255)  // 1A1814
    static let textSecondary = Color(red: 122/255, green: 117/255, blue: 111/255) // 7A756F
    static let textFaint    = Color(red: 176/255, green: 169/255, blue: 159/255) // B0A99F

    static let yes          = Color(red: 123/255, green: 184/255, blue: 154/255) // 7BB89A
    static let yesFill      = Color(red: 196/255, green: 224/255, blue: 212/255) // C4E0D4
    static let no           = Color(red: 201/255, green: 123/255, blue: 123/255) // C97B7B
    static let noFill       = Color(red: 245/255, green: 206/255, blue: 206/255) // F5CECE
    static let accent       = Color(red: 232/255, green: 160/255, blue: 160/255) // E8A0A0

    static let dark         = Color(red: 26/255,  green: 24/255,  blue: 20/255)  // 1A1814
}

// MARK: - Event Status

enum EventStatus: String, CaseIterable {
    case live = "LIVE"
    case betsClosed = "BETS CLOSED"
    case resolved = "RESOLVED"
    case cancelled = "CANCELLED"

    var dotColor: Color {
        switch self {
        case .live:        return ClipBetColors.accent
        case .betsClosed:  return ClipBetColors.textSecondary
        case .resolved:    return ClipBetColors.yes
        case .cancelled:   return ClipBetColors.textFaint
        }
    }

    var isPulsing: Bool {
        self == .live
    }
}

// MARK: - Betting Window

enum BettingWindow: String {
    case manual = "Close Manually"
    case atStart = "Close at Start"
    case stayOpen = "Stay Open During Event"
}

// MARK: - Bet Outcome (Option)

struct BetOutcome: Identifiable, Hashable {
    let id: UUID
    let name: String
    var totalAmount: Double
    var betCount: Int

    var formattedAmount: String {
        String(format: "$%.0f", totalAmount)
    }
}

// MARK: - Prediction Event

struct PredictionEvent: Identifiable {
    let id: UUID
    let name: String
    let location: String
    let locationLat: Double
    let locationLng: Double
    let organizer: String
    let organizerId: UUID
    var status: EventStatus
    var outcomes: [BetOutcome]
    let minimumBet: Double
    let bettingWindow: BettingWindow
    let createdAt: Date
    var startedAt: Date?
    var closedAt: Date?
    var resolvedAt: Date?
    var resolvedOutcomeId: UUID?

    // Pool calculations

    var totalPool: Double {
        outcomes.reduce(0) { $0 + $1.totalAmount }
    }

    var totalBettors: Int {
        outcomes.reduce(0) { $0 + $1.betCount }
    }

    var platformFee: Double {
        totalPool * 0.05
    }

    var winnerPool: Double {
        totalPool - platformFee
    }

    func percentage(for outcome: BetOutcome) -> Double {
        guard totalPool > 0 else { return 0 }
        return (outcome.totalAmount / totalPool) * 100
    }

    func estimatedReturn(betAmount: Double, for outcome: BetOutcome) -> Double {
        let newOutcomeTotal = outcome.totalAmount + betAmount
        let newPoolTotal = totalPool + betAmount
        let winnerPoolAfterFee = newPoolTotal * 0.95
        return (betAmount / newOutcomeTotal) * winnerPoolAfterFee
    }

    var formattedPool: String {
        String(format: "$%.0f", totalPool)
    }

    var timeSinceCreated: String {
        let interval = Date().timeIntervalSince(createdAt)
        let minutes = Int(interval) / 60
        let hours = minutes / 60
        if hours > 0 {
            return "\(hours)h \(minutes % 60)m"
        }
        return "\(minutes)m"
    }
}

// MARK: - Bet Status

enum BetStatus: String {
    case pending = "Pending"
    case confirmed = "Confirmed"
    case won = "Won"
    case lost = "Lost"
    case refunded = "Refunded"
}

// MARK: - Payout Status

enum PayoutStatus: String {
    case none = "None"
    case processing = "Processing"
    case completed = "Completed"
    case failed = "Failed"
}

// MARK: - User Bet

struct UserBet: Identifiable {
    let id: UUID
    let eventId: UUID
    let outcomeId: UUID
    let amount: Double
    let nickname: String
    let email: String
    var status: BetStatus
    var payoutAmount: Double?
    var payoutStatus: PayoutStatus
    let createdAt: Date
    var stripePaymentIntentId: String?
}

// MARK: - Organizer

struct EventOrganizer: Identifiable {
    let id: UUID
    let appleUserId: String
    var stripeConnectId: String?
    let tosAgreedAt: Date?
    let verifiedAt: Date?
    var eventsCreated: Int
    var disputesAgainst: Int
    var rating: Double

    var isVerified: Bool {
        verifiedAt != nil && stripeConnectId != nil
    }

    var isFirstTime: Bool {
        tosAgreedAt == nil
    }
}

// MARK: - Dispute

enum DisputeStatus: String {
    case open = "Open"
    case resolved = "Resolved"
    case rejected = "Rejected"
}

struct BetDispute: Identifiable {
    let id: UUID
    let eventId: UUID
    let bettorId: UUID
    let reason: String
    var status: DisputeStatus
    let createdAt: Date
    var resolvedAt: Date?
    var resolution: String?
}

// MARK: - From Submissions/clipbet/ClipBetPayment.swift

//  ClipBetPayment.swift
//  ClipBet
//
//  Payment manager handling Apple Pay (user-facing) with
//  Stripe as the invisible backend. Users never see Stripe.
//
//  In production:
//    Apple Pay -> PKPaymentRequest -> Stripe PaymentIntent -> Escrow
//    Resolve -> Stripe Connect transfers to winners
//    Cancel -> Stripe refunds to original payment methods
//
//  For hackathon demo: fully mocked with realistic states.
//

import SwiftUI

// MARK: - Payment State

enum PaymentState: Equatable {
    case idle
    case processing
    case success(transactionId: String)
    case failed(message: String)
    case refunded
}

// MARK: - Payment Method

enum PaymentMethod: String {
    case applePay = "Apple Pay"
    case card = "Card"
}

// MARK: - Escrow State

enum EscrowState: String {
    case pending = "Pending"
    case held = "Held"
    case distributing = "Distributing"
    case distributed = "Distributed"
    case refunding = "Refunding"
    case refunded = "Refunded"
}

// MARK: - Payment Manager

@Observable
final class ClipBetPaymentManager {

    var paymentState: PaymentState = .idle
    var selectedMethod: PaymentMethod = .applePay
    var escrowState: EscrowState = .pending

    // In production this would be the Stripe PaymentIntent ID
    private(set) var paymentIntentId: String?

    // Platform fee percentage
    let platformFeeRate: Double = 0.05

    // MARK: - Process Bet Payment

    /// Processes a bet payment. In production this would:
    /// 1. Create a Stripe PaymentIntent on the backend
    /// 2. Present Apple Pay sheet (PKPaymentAuthorizationViewController)
    /// 3. Confirm the PaymentIntent with the Apple Pay token
    /// 4. Hold funds in escrow on the platform Stripe account
    func processBet(
        amount: Double,
        eventId: UUID,
        outcomeId: UUID,
        email: String,
        nickname: String,
        completion: @escaping (Bool) -> Void
    ) {
        paymentState = .processing

        // Mock: simulate network delay for PaymentIntent creation + Apple Pay
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) { [weak self] in
            guard let self else { return }

            // Simulate 95% success rate
            let success = Double.random(in: 0...1) < 0.95

            if success {
                let txId = "pi_\(UUID().uuidString.prefix(8))"
                self.paymentIntentId = txId
                self.paymentState = .success(transactionId: txId)
                self.escrowState = .held
                completion(true)
            } else {
                self.paymentState = .failed(message: "Payment could not be completed. Please try again.")
                completion(false)
            }
        }
    }

    // MARK: - Distribute Winnings

    /// Called when organizer resolves the event. In production:
    /// 1. Backend calculates each winner's share
    /// 2. Deducts 5% platform fee
    /// 3. Creates Stripe Connect transfers to winner payment methods
    /// 4. Organizer gets their fee share via Stripe Connect
    func distributeWinnings(
        event: PredictionEvent,
        winningOutcomeId: UUID,
        completion: @escaping ([(nickname: String, payout: Double)]) -> Void
    ) {
        escrowState = .distributing

        DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) { [weak self] in
            guard let self else { return }
            guard let winningOutcome = event.outcomes.first(where: { $0.id == winningOutcomeId }) else {
                return
            }

            let totalPool = event.totalPool
            let fee = totalPool * self.platformFeeRate
            let winnerPool = totalPool - fee

            // Parimutuel: each winner gets proportional share
            // In production, each individual bet amount is tracked
            let payoutPerDollar = winnerPool / winningOutcome.totalAmount

            // Mock payout list
            let payouts: [(nickname: String, payout: Double)] = [
                ("Winner1", 25.0 * payoutPerDollar),
                ("Winner2", 10.0 * payoutPerDollar),
            ]

            self.escrowState = .distributed
            completion(payouts)
        }
    }

    // MARK: - Process Refund

    /// Called when organizer cancels or 24h resolution window expires.
    /// In production: triggers Stripe refunds to original payment methods.
    func processRefund(completion: @escaping (Bool) -> Void) {
        escrowState = .refunding

        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { [weak self] in
            self?.escrowState = .refunded
            self?.paymentState = .refunded
            completion(true)
        }
    }

    // MARK: - Reset

    func reset() {
        paymentState = .idle
        paymentIntentId = nil
        escrowState = .pending
    }
}

// MARK: - Apple Pay Button View

struct ClipBetApplePayButton: View {
    let amount: Double
    let isEnabled: Bool
    let isProcessing: Bool
    let onTap: () -> Void
    let onCardFallback: () -> Void

    var body: some View {
        VStack(spacing: 12) {
            // Primary: Apple Pay
            Button(action: onTap) {
                HStack(spacing: 8) {
                    if isProcessing {
                        ProgressView()
                            .tint(ClipBetColors.dark)
                    } else {
                        Image(systemName: "apple.logo")
                            .font(.system(size: 18))
                        Text("PAY WITH APPLE PAY")
                            .font(.custom("DM Mono", size: 13))
                            .kerning(2)
                    }
                }
                .foregroundColor(ClipBetColors.dark)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 18)
                .background(Color.white)
                .clipShape(RoundedRectangle(cornerRadius: 2))
            }
            .disabled(!isEnabled || isProcessing)
            .opacity(isEnabled ? 1.0 : 0.5)

            // Fallback: Pay with card (still Stripe underneath, no branding)
            Button(action: onCardFallback) {
                Text("or pay with card")
                    .font(.custom("DM Mono", size: 11))
                    .foregroundColor(ClipBetColors.textFaint)
                    .underline()
            }
            .disabled(!isEnabled || isProcessing)
        }
    }
}

// MARK: - Payment Status View

struct ClipBetPaymentStatus: View {
    let state: PaymentState

    var body: some View {
        switch state {
        case .idle:
            EmptyView()

        case .processing:
            HStack(spacing: 8) {
                ProgressView()
                    .tint(ClipBetColors.textSecondary)
                Text("PROCESSING")
                    .font(.custom("DM Mono", size: 10))
                    .kerning(1.6)
                    .foregroundColor(ClipBetColors.textSecondary)
            }
            .padding(.vertical, 8)

        case .success(let txId):
            VStack(spacing: 4) {
                HStack(spacing: 6) {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.system(size: 12))
                        .foregroundColor(ClipBetColors.yes)
                    Text("PAYMENT CONFIRMED")
                        .font(.custom("DM Mono", size: 10))
                        .kerning(1.6)
                        .foregroundColor(ClipBetColors.yes)
                }
                Text(txId)
                    .font(.custom("DM Mono", size: 9))
                    .foregroundColor(ClipBetColors.textFaint)
            }
            .padding(.vertical, 8)

        case .failed(let message):
            VStack(spacing: 4) {
                HStack(spacing: 6) {
                    Image(systemName: "xmark.circle.fill")
                        .font(.system(size: 12))
                        .foregroundColor(ClipBetColors.no)
                    Text("PAYMENT FAILED")
                        .font(.custom("DM Mono", size: 10))
                        .kerning(1.6)
                        .foregroundColor(ClipBetColors.no)
                }
                Text(message)
                    .font(.custom("DM Mono", size: 10))
                    .foregroundColor(ClipBetColors.textSecondary)
                    .multilineTextAlignment(.center)
            }
            .padding(.vertical, 8)

        case .refunded:
            HStack(spacing: 6) {
                Image(systemName: "arrow.uturn.backward.circle.fill")
                    .font(.system(size: 12))
                    .foregroundColor(ClipBetColors.textSecondary)
                Text("REFUNDED")
                    .font(.custom("DM Mono", size: 10))
                    .kerning(1.6)
                    .foregroundColor(ClipBetColors.textSecondary)
            }
            .padding(.vertical, 8)
        }
    }
}

