//  GeneratedSubmissions.swift
//  ReactivChallengeKit
//
//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved.
//

/// Auto-generated by scripts/generate-registry.sh — do not edit manually.

// MARK: - From Submissions/northreport/NorthReportExperience.swift

import SwiftUI
import PhotosUI
import CoreLocation

// MARK: - NorthReport Clip Experience
// Civic issue reporting in under 30 seconds. Scan a QR code at any public
// space, snap a photo of the issue, and AI classifies + files the report
// automatically. No app install, no account, no friction.

struct NorthReportExperience: ClipExperience {
    static let urlPattern = "northreport.app/report/:neighborhood"
    static let clipName = "NorthReport"
    static let clipDescription = "Snap a photo of a civic issue — AI classifies and files your report in seconds."
    static let teamName = "NorthReport"
    static let touchpoint: JourneyTouchpoint = .onSite
    static let invocationSource: InvocationSource = .qrCode

    let context: ClipContext

    @State private var step: ReportStep = .capture
    @State private var selectedPhoto: PhotosPickerItem?
    @State private var capturedImage: UIImage?
    @State private var description: String = ""
    @State private var locationLabel: String = "Detecting location..."
    @State private var locationReady = false
    @State private var submitting = false
    @State private var resultMessage: String = ""
    @State private var resultCategory: String = ""
    @State private var resultSeverity: String = ""

    private var neighborhood: String {
        context.pathParameters["neighborhood"]?.replacingOccurrences(of: "-", with: " ").capitalized
            ?? "Downtown Waterloo"
    }

    enum ReportStep {
        case capture, review, success
    }

    var body: some View {
        ZStack {
            NorthReportBackground()

            switch step {
            case .capture:
                captureView
                    .transition(.opacity)
            case .review:
                reviewView
                    .transition(.move(edge: .trailing).combined(with: .opacity))
            case .success:
                successView
                    .transition(.scale.combined(with: .opacity))
            }
        }
        .animation(.spring(duration: 0.35), value: step)
        .onChange(of: selectedPhoto) { _, item in
            guard let item else { return }
            Task {
                if let data = try? await item.loadTransferable(type: Data.self),
                   let img = UIImage(data: data) {
                    capturedImage = img
                    withAnimation(.spring(duration: 0.35)) {
                        step = .review
                    }
                    simulateLocationDetection()
                }
            }
        }
    }

    // MARK: - Capture View

    private var captureView: some View {
        VStack(spacing: 24) {
            Spacer()

            Image(systemName: "camera.viewfinder")
                .font(.system(size: 56, weight: .thin))
                .foregroundStyle(.primary.opacity(0.6))

            VStack(spacing: 8) {
                Text("Report an Issue")
                    .font(.system(size: 24, weight: .bold))
                    .foregroundStyle(.primary)
                Text("Take a photo of the problem near\n\(neighborhood)")
                    .font(.system(size: 14))
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
            }

            Spacer()

            PhotosPicker(selection: $selectedPhoto, matching: .images) {
                HStack(spacing: 10) {
                    Image(systemName: "camera.fill")
                        .font(.system(size: 18, weight: .semibold))
                    Text("Take Photo")
                        .font(.system(size: 17, weight: .semibold))
                }
                .foregroundStyle(.white)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 16)
                .background(Color.green.opacity(0.85), in: RoundedRectangle(cornerRadius: 16))
            }
            .padding(.horizontal, 24)
            .padding(.bottom, 16)
        }
    }

    // MARK: - Review View

    private var reviewView: some View {
        VStack(spacing: 0) {
            // Header
            HStack {
                Text("Review")
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundStyle(.primary)
                Spacer()
                Button {
                    withAnimation(.spring(duration: 0.35)) {
                        capturedImage = nil
                        selectedPhoto = nil
                        step = .capture
                    }
                } label: {
                    Text("Retake")
                        .font(.system(size: 14, weight: .medium))
                        .foregroundStyle(.secondary)
                }
            }
            .padding(.horizontal, 20)
            .padding(.vertical, 10)

            // Photo preview
            if let image = capturedImage {
                Image(uiImage: image)
                    .resizable()
                    .scaledToFill()
                    .frame(height: 260)
                    .frame(maxWidth: .infinity)
                    .clipped()
                    .clipShape(RoundedRectangle(cornerRadius: 14))
                    .padding(.horizontal, 16)
            }

            // Controls
            VStack(spacing: 12) {
                // Description field
                HStack(spacing: 10) {
                    Image(systemName: "text.cursor")
                        .foregroundStyle(.secondary.opacity(0.6))
                        .font(.system(size: 14))
                    TextField("Describe the issue (optional)", text: $description)
                        .font(.subheadline)
                        .foregroundStyle(.primary)
                }
                .padding(12)
                .glassEffect(.regular.interactive(), in: RoundedRectangle(cornerRadius: 10))

                // Location row
                HStack(spacing: 6) {
                    if locationReady {
                        Circle()
                            .fill(Color.green.opacity(0.7))
                            .frame(width: 6, height: 6)
                    } else {
                        ProgressView()
                            .scaleEffect(0.5)
                            .frame(width: 6, height: 6)
                    }
                    Text(locationLabel)
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                    Spacer()
                }

                // Submit button
                Button {
                    Task { await submit() }
                } label: {
                    HStack(spacing: 8) {
                        if submitting {
                            ProgressView()
                                .tint(.white)
                                .scaleEffect(0.85)
                        } else {
                            Image(systemName: "arrow.up")
                                .font(.system(size: 14, weight: .semibold))
                            Text("Submit Report")
                                .font(.system(size: 16, weight: .semibold))
                        }
                    }
                    .foregroundStyle(.white)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 15)
                    .background(
                        (submitting || !locationReady)
                            ? Color.gray.opacity(0.5)
                            : Color.green.opacity(0.85),
                        in: RoundedRectangle(cornerRadius: 12)
                    )
                }
                .disabled(submitting || !locationReady)
            }
            .padding(.horizontal, 20)
            .padding(.top, 12)
            .padding(.bottom, 16)
        }
    }

    // MARK: - Success View

    private var successView: some View {
        VStack(spacing: 20) {
            Spacer()

            ClipSuccessOverlay(message: "Report Filed")

            if !resultCategory.isEmpty {
                GlassEffectContainer {
                    VStack(spacing: 8) {
                        infoRow(icon: "tag.fill", label: "Category", value: resultCategory)
                        infoRow(icon: "exclamationmark.triangle.fill", label: "Severity", value: resultSeverity)
                    }
                }
                .padding(.horizontal, 20)
            }

            if !resultMessage.isEmpty {
                Text(resultMessage)
                    .font(.system(size: 14))
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 32)
            }

            Spacer()

            ClipActionButton(title: "Report Another", icon: "plus.circle.fill") {
                withAnimation(.spring(duration: 0.35)) {
                    capturedImage = nil
                    selectedPhoto = nil
                    description = ""
                    resultMessage = ""
                    resultCategory = ""
                    resultSeverity = ""
                    locationReady = false
                    locationLabel = "Detecting location..."
                    step = .capture
                }
            }

            Spacer().frame(height: 8)
        }
    }

    // MARK: - Helpers

    @ViewBuilder
    private func infoRow(icon: String, label: String, value: String) -> some View {
        HStack {
            Label(label, systemImage: icon)
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(.secondary)
            Spacer()
            Text(value.capitalized)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(.primary)
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 8)
        .glassEffect(.regular.interactive(), in: RoundedRectangle(cornerRadius: 12))
    }

    private func simulateLocationDetection() {
        locationReady = false
        locationLabel = "Detecting location..."
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
            withAnimation(.easeInOut(duration: 0.3)) {
                locationLabel = "\(neighborhood)"
                locationReady = true
            }
        }
    }

    // MARK: - API Submission

    private func submit() async {
        guard let image = capturedImage else { return }
        submitting = true

        // Resize + compress to stay under Vercel's 4.5MB body limit
        let resized = NorthReportImageUtils.resize(image, maxWidth: 1200)
        guard let data = resized.jpegData(compressionQuality: 0.3) else {
            submitting = false
            return
        }
        let base64 = data.base64EncodedString()

        let url = URL(string: "https://hackcanada-psi.vercel.app/api/clip-report")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("nr-clip-2025-hackcanada", forHTTPHeaderField: "x-clip-key")
        request.timeoutInterval = 30

        let body: [String: Any] = [
            "imageBase64": "data:image/jpeg;base64,\(base64)",
            "latitude": 43.4530,
            "longitude": -80.4990,
            "description": description
        ]

        do {
            request.httpBody = try JSONSerialization.data(withJSONObject: body)
            let (responseData, httpResponse) = try await URLSession.shared.data(for: request)

            if let decoded = try? JSONDecoder().decode(NorthReportAPIResponse.self, from: responseData),
               (httpResponse as? HTTPURLResponse)?.statusCode == 201 {
                resultCategory = decoded.category ?? "infrastructure"
                resultSeverity = decoded.severity ?? "medium"
                resultMessage = decoded.aiSummary ?? "Report submitted successfully."
            } else {
                resultMessage = "Report queued for review."
                resultCategory = "pending"
                resultSeverity = "tbd"
            }
        } catch {
            resultMessage = "Report saved locally. Will sync when online."
            resultCategory = "pending"
            resultSeverity = "tbd"
        }

        withAnimation(.spring(duration: 0.35)) {
            submitting = false
            step = .success
        }
    }
}

// MARK: - API Response

private struct NorthReportAPIResponse: Codable {
    let id: String?
    let category: String?
    let severity: String?
    let aiSummary: String?
    let message: String?
    let error: String?
}

// MARK: - Image Utilities

private enum NorthReportImageUtils {
    static func resize(_ image: UIImage, maxWidth: CGFloat) -> UIImage {
        guard image.size.width > maxWidth else { return image }
        let scale = maxWidth / image.size.width
        let newSize = CGSize(width: maxWidth, height: image.size.height * scale)
        let renderer = UIGraphicsImageRenderer(size: newSize)
        return renderer.image { _ in image.draw(in: CGRect(origin: .zero, size: newSize)) }
    }
}

// MARK: - Background

private struct NorthReportBackground: View {
    var body: some View {
        ZStack {
            Color(.systemBackground)

            LinearGradient(
                colors: [
                    Color.green.opacity(0.15),
                    Color.mint.opacity(0.1),
                    .clear,
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )

            RadialGradient(
                colors: [
                    Color.green.opacity(0.08),
                    .clear,
                ],
                center: .bottomTrailing,
                startRadius: 40,
                endRadius: 420
            )
        }
        .ignoresSafeArea()
    }
}

