#!/usr/bin/env bash
# Generates SubmissionRegistry.swift from Submissions folder.
# Called by Xcode build phase; SRCROOT is set by Xcode.

set -e
SUBMISSIONS_ROOT="${SRCROOT}/../Submissions"
OUTPUT="${SRCROOT}/Source/SubmissionRegistry.swift"

NAMES=()
if [[ -d "$SUBMISSIONS_ROOT" ]]; then
  for f in "${SUBMISSIONS_ROOT}"/*/*.swift; do
    [[ -f "$f" ]] || continue
    [[ "$f" == *"/_template/"* ]] && continue
    while IFS= read -r line; do
      if [[ "$line" =~ struct[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*:[[:space:]]*ClipExperience ]]; then
        NAMES+=("${BASH_REMATCH[1]}")
        break
      fi
    done < "$f"
  done
fi

{
  echo "//  SubmissionRegistry.swift"
  echo "//  ReactivChallengeKit"
  echo "//"
  echo "//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved."
  echo "//"
  echo ""
  echo "/// Auto-generated by scripts/generate-registry.sh — do not edit manually."
  echo "enum SubmissionRegistry {"
  echo "    static let all: [any ClipExperience.Type] = ["
  for name in "${NAMES[@]}"; do
    echo "        ${name}.self,"
  done
  echo "    ]"
  echo "}"
} > "$OUTPUT"
